// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	//
	// = 1; is a tag
	// tags are used for encoding binary
	// tags 1-15 can be encoded using 1 less byte, so it is worth it to put commonly used or repeated elements in lower tags.
	// optional elements should be placed in higher tags
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	// Repeated fields are like dynamically sized arrays
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=main.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "main.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "main.AddressBook")
	proto.RegisterEnum("main.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0xf4, 0xd2, 0xeb, 0x61, 0x37, 0x52, 0xe2, 0x22, 0xe5, 0xf0, 0x29, 0x04, 0x1f, 0x82, 0x42,
	0x90, 0xf6, 0x0b, 0x2c, 0x14, 0x14, 0xad, 0xa9, 0x87, 0xe0, 0x73, 0x42, 0x0e, 0x0c, 0x6d, 0x6e,
	0x8f, 0xa4, 0x3e, 0xf4, 0xbf, 0xfd, 0x00, 0xb9, 0x4b, 0x90, 0x40, 0xdf, 0x66, 0x77, 0x87, 0x99,
	0x9d, 0x81, 0xeb, 0xa2, 0xaa, 0x5a, 0xdd, 0x75, 0x25, 0xd1, 0x3e, 0xb3, 0x2d, 0x1d, 0x09, 0x79,
	0x53, 0xd4, 0x26, 0xf9, 0x65, 0x20, 0x76, 0xba, 0xed, 0xc8, 0x20, 0x02, 0x37, 0x45, 0xa3, 0x25,
	0x8b, 0x59, 0x3a, 0x53, 0x1e, 0xe3, 0x1c, 0x82, 0xba, 0x92, 0x41, 0xcc, 0xd2, 0xa9, 0x0a, 0xea,
	0x0a, 0x6f, 0x60, 0xaa, 0x9b, 0xa2, 0x3e, 0xc8, 0x89, 0x27, 0xf5, 0x03, 0x3e, 0x82, 0xb0, 0xdf,
	0x64, 0x74, 0x27, 0x79, 0x3c, 0x49, 0xc3, 0xa5, 0xcc, 0x9c, 0x76, 0xd6, 0xeb, 0x66, 0x3b, 0x77,
	0x7a, 0xff, 0x69, 0x4a, 0xdd, 0xaa, 0x81, 0x77, 0xfb, 0x01, 0xe1, 0x68, 0x8d, 0x0b, 0x10, 0xc6,
	0xa3, 0xc1, 0x7c, 0x98, 0xf0, 0x1e, 0xf8, 0xf1, 0x64, 0xb5, 0x7f, 0x60, 0xbe, 0x5c, 0x9c, 0xcb,
	0x7e, 0x9e, 0xac, 0x56, 0x9e, 0x93, 0x3c, 0xc0, 0xec, 0x7f, 0x85, 0x00, 0x62, 0x9b, 0xaf, 0x5f,
	0xde, 0x36, 0xd1, 0x05, 0x5e, 0x02, 0x7f, 0xce, 0xb7, 0x9b, 0x88, 0x39, 0xf4, 0x95, 0xab, 0xd7,
	0x28, 0x48, 0x56, 0x10, 0x3e, 0xf5, 0x8d, 0xac, 0x89, 0xf6, 0x78, 0x07, 0xc2, 0x6a, 0xb2, 0x07,
	0x17, 0xde, 0x05, 0xb8, 0x1a, 0x3b, 0xa9, 0xe1, 0x56, 0x0a, 0x5f, 0xdc, 0xea, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x6d, 0x9e, 0x14, 0xc1, 0x4d, 0x01, 0x00, 0x00,
}
